### ISSUE TITLE
Changes in README.md file

### ISSUE THREAD

**Issue by JokerPhoenix05** [NoxFly/canvas#3]
Changes in README.md file.

under **Mouse Properties**.

Change 
```javascript
function mouseMouse(e) { 
    // called when the mouse move on the canvas
 }
```
To
```javascript
function mouseMove(e) { 
    // called when the mouse move on the canvas
 }
```

**Comment by NoxFly** [comment]
which changes did you do ? I don't see any difference

**Comment by JokerPhoenix05** [comment]
I not did any changes. See the README.MD file. You misspell  mouseMove as mouseMouse.

**Comment by NoxFly** [comment]
well seen, indeed I did a mistake for the function name. Thanks.

**Comment by JokerPhoenix05** [comment]
Welcome ☺
